# Generated by Django 4.0.3 on 2022-05-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idServicio', models.IntegerField()),
                ('nombreProfesional', models.CharField(max_length=100)),
                ('nombreEstudiante', models.CharField(max_length=100)),
                ('codigoEstudiante', models.CharField(max_length=100)),
                ('edificio', models.CharField(max_length=50)),
                ('salon', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=100)),
            ],
        ),
    ]
